multi-tenancy:
  tenants:

    - id: master
      mongo:
        authentication-database: admin
        database: master
        username: admin
        password: admin

    - id: tenant-1
      mongo:
        authentication-database: admin
        database: tenant1
        username: admin
        password: admin

    - id: tenant-2
      mongo:
        authentication-database: admin
        database: tenant2
        username: admin
        password: admin
