multi-tenancy:
  tenants:

    - id: master
      mongo:
        authentication-database: admin
        database: master
        username: admin
        password: admin

    - id: customer-1
      mongo:
        authentication-database: admin
        database: customer1data
        username: root
        password: example

    - id: customer-2
      mongo:
        authentication-database: admin
        database: customer2data
        username: root
        password: example
